import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mesa para Dos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NavBar/>

        {children}
      </body>
    </html>
  );
}

//!layout para navbar chatGPT
// import "./globals.css";
// import { NavBar } from "@/components/navbar/NavBar"; // ajustá la ruta

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="es">
//       <body className="bg-gray-950 text-gray-100">
//         <NavBar />
//         <main className="mx-auto max-w-6xl px-4 py-6">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }
